std::map<std::wstring, const char*> mineTypeData = {
{L"html", "text/html"},
{L"htm", "text/html"},
{L"shtml", "text/html"},
{L"css", "text/css"},
{L"xml", "text/xml" },
{L"gif", "image/gif"},
{L"jpeg jpg", "image/jpeg"         },
{L"js", "application/javascript"   },
{L"atom", "application/atom+xml"     },
{L"rss", "application/rss+xml"       },
{L"mml", "text/mathml"},
{L"txt", "text/plain"},
{L"jad", "text/vnd.sun.j2me.app-descriptor"},
{L"wml", "text/vnd.wap.wml"},
{L"htc", "text/x-component"},
{L"avif", "image/avif"      },
{L"png", "image/png"        },
{L"svg", "image/svg+xml  "},
{L"svgz", "image/svg+xml  "},
{L"tif tiff", "image/tiff     "},
{L"wbmp", "image/vnd.wap.wbmp "},
{L"webp", "image/webp         "},
{L"ico", "image/x-icon"},
{L"jng", "image/x-jng"},
{L"bmp", "image/x-ms-bmp"},
{L"woff", "font/woff"},
{L"woff2", "font/woff2"},
{L"jar", "application/java-archive"},
{L"war", "application/java-archive"},
{L"ear", "application/java-archive"},
{L"json", "application/json"},
{L"hqx", "application/mac-binhex40 "},
{L"doc", "application/msword"},
{L"pdf", "application/pdf"},
{L"ps", "application/postscript"},
{L"eps", "application/postscript"},
{L"ai", "application/postscript"},
{L"rtf", "application/rtf"},
{L"m3u8", "application/vnd.apple.mpegurl"},
{L"kml", "application/vnd.google-earth.kml+xml"},
{L"kmz", "application/vnd.google-earth.kmz"},
{L"xls", "application/vnd.ms-excel"},
{L"eot", "application/vnd.ms-fontobject"},
{L"ppt", "application/vnd.ms-powerpoint" },
{L"odg", "application/vnd.oasis.opendocument.graphics"},
{L"odp", "application/vnd.oasis.opendocument.presentation" },
{L"ods", "application/vnd.oasis.opendocument.spreadsheet"  },
{L"odt", "application/vnd.oasis.opendocument.text"         },
{L"pptx", 	"application/vnd.openxmlformats-officedocument.presentationml.presentatio"},
{L"xlsx",	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
{L"docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.documen"},
{L"wmlc", 	"application/vnd.wap.wmlc"},
{L"wasm", 	"application/wasm"},
{L"7z", 	"application/x-7z-compressed"},
{L"cco", 	"application/x-cocoa"},
{L"jardiff", 	"application/x-java-archive-diff"},
{L"jnlp", 	"application/x-java-jnlp-file"},
{L"run", 	"application/x-makeself"},
{L"pl pm", 	"application/x-perl"},
{L"prc pdb", 	"application/x-pilot"},
{L"rar", 	"application/x-rar-compressed"},
{L"rpm", 	"application/x-redhat-package-manager"},
{L"sea", 	"application/x-sea"},
{L"swf", 	"application/x-shockwave-flash"},
{L"sit", 	"application/x-stuffit"},
{L"tcl tk", 	"application/x-tcl"},
{L"der pem crt", 	"application/x-x509-ca-cert  "},
{L"xpi", 	"application/x-xpinstall"},
{L"xhtml", 	"application/xhtml+xml"},
{L"xspf", 	"application/xspf+xml"},
{L"zip", 	"application/zip"},
{L"bin exe dll", 	"application/octet-stream"},
{L"deb", 	"application/octet-stream"},
{L"dmg", 	"application/octet-stream"},
{L"iso img", 	"application/octet-stream"},
{L"msi msp msm", 	"application/octet-stream"},
{L"mid midi kar", 	"audio/midi"},
{L"mp3", 	"audio/mpeg"},
{L"ogg", 	"audio/ogg "},
{L"m4a", 	"audio/x-m4a"},
{L"ra", 	"audio/x-realaudio"},
{L"3gpp 3gp", 	"video/3gpp"},
{L"ts", 	"video/mp2t"},
{L"mp4", 	"video/mp4"},
{L"mpeg mpg", 	"video/mpeg"},
{L"mov", 	"video/quicktime"},
{L"webm", 	"video/webm"},
{L"flv", 	"video/x-flv"},
{L"m4v", 	"video/x-m4v"},
{L"mng", 	"video/x-mng"},
{L"asx asf", 	"video/x-ms-asf"},
{L"wmv", 	"video/x-ms-wmv"},
{L"avi", 	"video/x-msvideo"}
};

const char* getType(const WCHAR* name) {
	auto s = PathFindExtensionW(name);
	if (s == NULL) {
		return "text/plain; charset=utf-8";
	}
	s++;
	auto r = mineTypeData.find(s);
	if (r == mineTypeData.end())
		return "text/plain; charset=utf-8";
	return r->second;
}
